# PureVox - Windows packaging script (PyInstaller bundle)
# Output: dist/PureVox/  (PyInstaller one-folder bundle; CI uploads this dir and
#                        GitHub artifacts compress it to a .zip automatically)
# Usage:  powershell -ExecutionPolicy Bypass -File build_win.ps1
$ErrorActionPreference = "Stop"

# Version stamp shown in the window title. Single source: tools/automation/version.ps1
# (tag runs take it from GITHUB_REF_NAME so the title matches the tag /
# artifact filename; local builds fall back to the current UTC time).
# (Pure ASCII: PS 5.1 / Win7 safe.)
. (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "tools\automation\version.ps1")
$date = $STAMP

# Prefer the bundled Python 3.12 (generated by bootstrap_python312.ps1 in packages\python312w)
# so the build is independent of the system Python. Fall back to python on PATH.
$embeddedPy = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "packages\python312w\python.exe"
if (Test-Path $embeddedPy) {
    $PY = $embeddedPy
} else {
    $PY = "python"
}

# 1. Generate version stamp (shown in the window title)
#    -NoNewline is PowerShell 6+/7 only; Win7 ships PS 5.1, so write without it
#    (a trailing newline in _build_version.py is harmless).
Set-Content _build_version.py "BUILD_DATE = `"$date`"" -Encoding UTF8

# 2. PyInstaller packaging
#    lazy-imported modules must be hidden-import (function-level `from xx import` is not
#    discovered statically). The UI is the pure-Tkinter app (run_tk.py + uitk/);
#    tcl/tk support is collected automatically and MUST be kept in the bundle.
& $PY -m PyInstaller --clean --name PureVox --noconsole --icon=assets\icons\audio_icon.ico `
    --hidden-import=pyaudio `
    --hidden-import=audio_processor `
    --hidden-import=wav_io `
    --hidden-import=miniaudio `
    --hidden-import=pvplatform.audio.pwpipe_client `
    --collect-all=pycaw `
    --collect-all=comtypes `
    --add-data="about;about" `
    --add-data="models\*.onnx;models" `
    --add-data="assets\icons\audio_icon.ico;assets\icons" `
    --add-data="assets\icons\fader.png;assets\icons" `
    --add-data="assets\fonts\*.ttf;assets\fonts" `
    --add-data="html\*.html;html\" `
    --add-data="html\css\*.css;html\css\" `
    --add-data="html\js\*.js;html\js\" `
    --add-data="html\wasm\*;html\wasm\" `
    --add-data="server\*.py;server\" `
    --add-data="server\opus.dll;server\" `
    --exclude-module=pandas,matplotlib,unittest,tensorflow,torch,PySide6,PyQt5 `
    -y run_tk.py
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }

# 3. Keep tcl/tk data files: the Tkinter UI loads them at runtime (removing
#    them breaks startup with "no display / init.tcl not found").
# MSVC runtime DLLs ship with the bundle so no separate VC++ redistributable needed.
foreach ($vc in @("msvcp140.dll", "msvcp140_1.dll", "vcruntime140.dll", "vcruntime140_1.dll")) {
    $src = Join-Path $env:WINDIR ("System32\" + $vc)
    if (-not (Test-Path "dist\PureVox\_internal\$vc")) {
        if (Test-Path $src) {
            Copy-Item $src "dist\PureVox\_internal\$vc" -Force
            Write-Host "VC runtime copied: $vc"
        }
    }
}

# (no doc copy step: the About dialog embeds the manuals and the changelog
#  entirely in about_content.py; CHANGELOG.md / user-manual html are deleted)

Write-Host "==> Done: dist/PureVox"
